### ISSUE TITLE
Status Code 404

### ISSUE THREAD

**Issue by kispista17** [igolaizola/bulkai#25]
![341818144_1418626728677035_8534232492478587572_n](https://user-images.githubusercontent.com/89099233/235350057-2e2e76e6-8945-4ed3-8a4e-f398e0250cd7.png)

**Comment by igolaizola** [comment]
Messages can get deleted by midjourney if they detect that the output image violates any rules.
Here is someone with a similar issue https://www.reddit.com/r/midjourney/comments/11vzshn/all_jobs_in_discord_no_longer_allowing_emoji/

However, the tool should stop retrying when a "404 Not Found" is returned. So that is something that can be fixed.

**Comment by igolaizola** [comment]
Error handling of not found messages has been adder here: https://github.com/igolaizola/bulkai/pull/28
